name: example
description: Example usage of http_method code generation
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  http_method:
    path: ../

dev_dependencies:
  build_runner: ^2.3.2
