targets:
  $default:
    builders:
      http_method|networkBuilder:
        enabled: true

builders:
  networkBuilder:
    import: "package:http_method/src/generator/builder.dart"
    builder_factories: ["networkBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

