targets:
  $default:
    builders:
      component_generator|networkBuilder:
        enabled: true

builders:
  networkBuilder:
    import: "package:component_generator/src/generator/builder.dart"
    builder_factories: ["networkBuilder"]
    build_extensions: {".dart": [".network.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  widgetBuilder:
    import: "package:component_generator/src/generator/builder.dart"
    builder_factories: ["widgetBuilder"]
    build_extensions: {".dart": [".widget.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

